services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmanager-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-taskmanager}
      POSTGRES_USER: ${POSTGRES_USER:-taskmanager}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-taskmanager123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmanager -d taskmanager"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taskmanager-network

  taskmanager:
    image: alexiscreoulo/taskmanager:latest
    container_name: taskmanager
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Database configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-taskmanager}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-taskmanager}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-taskmanager123}
      SPRING_JPA_DDL_AUTO: ${SPRING_JPA_DDL_AUTO:-update}
      
      # JWT configuration
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      
      # Server configuration
      SERVER_PORT: ${SERVER_PORT:-8080}
      
      # Logging
      LOGGING_LEVEL_COM_PROJECTS_TASKMANAGER: ${LOGGING_LEVEL:-INFO}
      
      # File upload limits
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10MB}
      MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE:-10MB}
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - taskmanager-network

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  taskmanager-network:
    driver: bridge
