package com.projects.taskmanager.model;

public enum ActivityType {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_ASSIGNED,
    TASK_UNASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_DUE_DATE_CHANGED,
    TASK_ESTIMATION_CHANGED,
    COMMENT_ADDED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    ATTACHMENT_ADDED,
    ATTACHMENT_DELETED
}
